"use client";
import { useState } from "react";
import { Search, CheckCircle2, Clock3 } from "lucide-react";
import { Shell } from "@/components/shell";
import type { LandApplication } from "@/lib/types";

export default function ApplicationsPage(){
  const [tracking,setTracking]=useState('KZ-2026-042'); const [result,setResult]=useState<LandApplication|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function search(){setBusy(true);setError('');setResult(null);try{const r=await fetch(`/api/applications?tracking=${encodeURIComponent(tracking)}`);if(r.status===404){setError('Заявление не найдено');return;}const j=await r.json();setResult(j.application);}finally{setBusy(false)}}
  return <Shell title="Статусы заявлений" subtitle="Проверка трек-номеров, используемая Telegram-ботом"><main className="mx-auto max-w-4xl space-y-5 p-5 md:p-8"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Проверить заявление</h2><p className="mt-1 text-sm text-slate-500">Тестовые номера: KZ-2026-042 — KZ-2026-045</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><input value={tracking} onChange={e=>setTracking(e.target.value.toUpperCase())} className="flex-1 rounded-xl border border-slate-200 px-4 py-3 font-mono text-sm outline-none focus:border-slate-400"/><button disabled={busy} onClick={search} className="flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white"><Search size={16}/>{busy?'Проверяем...':'Проверить'}</button></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}</div>{result&&<div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs uppercase tracking-[0.18em] text-slate-400">{result.tracking_number}</div><h3 className="mt-2 text-2xl font-semibold">{result.status}</h3></div><div className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{result.stage}</div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><CheckCircle2 size={16}/> Текущий этап</div><p className="text-sm leading-6 text-slate-600">{result.description}</p></div><div className="rounded-xl bg-slate-50 p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Clock3 size={16}/> Ожидаемый срок</div><p className="text-sm text-slate-600">{result.eta}</p><p className="mt-2 text-xs text-slate-400">Обновлено {new Date(result.updated_at).toLocaleString('ru-RU')}</p></div></div></div>}</main></Shell>
}
